### ISSUE TITLE
msgpack is a dependency

### ISSUE THREAD

**Issue by tschoonj** [conda-forge/oslo.serialization-feedstock#13]
When running python-openstack client, build with conda, I encountered the following error (dozens of times):

```
Could not load EntryPoint.parse('federation_protocol_create = openstackclient.identity.v3.federation_protocol:CreateProtocol')
Traceback (most recent call last):
  File "/dls_sw/apps/python/anaconda/4.6.14/64/envs/openstack/lib/python2.7/site-packages/cliff/help.py", line 43, in __call__
    factory = ep.load()
  File "/dls_sw/apps/python/anaconda/4.6.14/64/envs/openstack/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2442, in load
    self.require(*args, **kwargs)
  File "/dls_sw/apps/python/anaconda/4.6.14/64/envs/openstack/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2465, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/dls_sw/apps/python/anaconda/4.6.14/64/envs/openstack/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
DistributionNotFound: The 'msgpack>=0.5.2' distribution was not found and is required by oslo.serialization

```

msgpack is indeed listed as a dependency in the [requirements.txt](https://github.com/openstack/oslo.serialization/blob/master/requirements.txt) file, so it should probably be added here too.

**Comment by brainstorm** [comment]
Sorry about that, could you craft a small PR? Happy to merge!
